name: taxiapplication
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  kf_drawer: ^1.1.2
  class_builder: ^1.0.1
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+3
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.13
  font_awesome_flutter: ^8.2.0
  geolocator: ^5.0.0
  google_map_polyline: 0.2.0+1
  great_circle_distance: ^1.0.1
  flutter_google_places: 0.2.4
  search_map_place: 0.1.1
  global_state: 0.1.2
  geocoder: 0.2.1
  permission: any
  location: ^2.3.5
  connectivity: 0.4.8+2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - assets/map_style.txt
    - assets/image/type1.png
    - assets/image/type2.png
    - assets/image/type3.png
    - assets/image/type4.png
    - assets/image/type5.png
    - assets/image/taxi.png
    - assets/image/distenation.png
    - assets/image/current.png
    - assets/image/route.png


  uses-material-design: true


